### ISSUE TITLE
Consider renaming "Invoker" to "Hosting"

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/functions-framework-dotnet#111]
The name "invoker" was taken from the Java Functions Framework. Most of ASP.NET Core uses "hosting" for this sort of thing - maybe we should fall in line? (So Google.Cloud.Functions.Hosting)

cc @grant for any thoughts.

**Comment by grant** [comment]
I like invoker a lot better

**Comment by jskeet** [comment]
@grant: Thanks. I'm getting feedback from a few other folks as well (in the .NET community).

**Comment by rsantosdev** [comment]
Hosting would be more aligned with the current asp.net core model

**Comment by jskeet** [comment]
@rsantosdev: Thanks for the feedback. I'll talk about this internally - I think it's going to be a matter of trying to be consistent with ASP.NET Core *or* consistent with other Functions Frameworks (I'm not sure how many refer to "invoker") so it'll be a balancing act.

**Comment by jskeet** [comment]
Decision: we'll rename to Google.Cloud.Functions.Hosting. Arguably we could rename the "Framework" package to be Google.Cloud.Functions.Abstractions, but we've decided that would be a step too far.

Will implement this with a new alpha release probably next week.

**Comment by jskeet** [comment]
Note: I'm renaming Google.Cloud.Functions.Invoker.Testing to Google.Cloud.Functions.Testing at the same time. It had already been bothering me a *bit* before, but it's much worse as Google.Cloud.Functions.Hosting.Testing.

No change in the content, just the namespace and package.

**Comment by jskeet** [comment]
This is now complete.
