### ISSUE TITLE
Implement --port and --target command line parameters

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/functions-framework-dotnet#13]
Currently, --port is not implemented and --target is first parameter. Implement them as proper command line parameters.

**Comment by jskeet** [comment]
How would you feel about "if there's only one argument and it doesn't start with --, just treat it as the target"? Just to keep the simple situation simple.

**Comment by jskeet** [comment]
It looks like we're inconsistent between Java and node as to whether it's `--target TargetName` or `--target=TargetName`. I could probably implement both, but I'm not sure it's a good idea. It's probably worth me talking to the FF team to see if we can gain some consistency.

**Comment by meteatamel** [comment]
I don't feel strongly about "one argument without -- being treated as the target" case either way.

Looking at [functions-framework](https://github.com/GoogleCloudPlatform/functions-framework), they give an example `--signature-type event` which implies that `=` is redundant.
