### ISSUE TITLE
Implement CloudEvents functions 

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/functions-framework-dotnet#14]
Implement CloudEvent functions as explained in [functions-framework](https://github.com/GoogleCloudPlatform/functions-framework#cloudevents-functions) and the `--signature-type` command line flag and `FUNCTION_SIGNATURE_TYPE` env variable.

**Comment by jskeet** [comment]
I don't think we'll need the --signature-type argument, as we can autodetect that from the method. But absolutely yes for implementing the feature in general :)

**Comment by jskeet** [comment]
Now released and documented as part of 1.0.0-alpha02.
