### ISSUE TITLE
CI: Add Conformance Workflow

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-dotnet#140]
I'm trying to run the conformance test script on this repo and am having some issues.

The end goal is to have a workflow running the conformance tests, that we can add to this table:
https://github.com/GoogleCloudPlatform/functions-framework#languages--test-status

I couldn't find the instructions for running the tests. This is what I tried:

---

I had to initialize a submodule for the conformance repo:

```
 git submodule update --init

Submodule 'functions-framework-conformance' (https://github.com/GoogleCloudPlatform/functions-framework-conformance) registered for path 'functions-framework-conformance'
Cloning into '/Users/timmerman/Documents/github/googlecloudplatform/functions-framework-dotnet/functions-framework-conformance'...
Submodule path 'functions-framework-conformance': checked out '3ae67138d9b0449975255b66d1f88f5c35eda763'
```

I then tried to run the conformance tests:

```
./run-conformance-tests.sh
Building conformance test framework
Building conformance functions
Running 'http' test with function 'HttpFunction'
./run-conformance-tests.sh: line 34: ../../../functions-framework-conformance/client/client.exe: No such file or directory
```

I'm not sure exactly what we're trying to do here, in terms of the path.

Ideally, we have CI that runs the conformance tests, similar to this setup:
https://github.com/GoogleCloudPlatform/functions-framework-go/blob/master/.github/workflows/main.yml#L23

I'm indifferent for using git submodules.

**Comment by jskeet** [comment]
Looks like the script only works on Windows right now - should be easy enough to fix; I'll get to it tomorrow.

**Comment by grant** [comment]
Cool, no rush.
