### ISSUE TITLE
Hooking into IWebHostBuilder

### ISSUE THREAD

**Issue by bruno-garcia** [GoogleCloudPlatform/functions-framework-dotnet#144]
I'm giving a try to extend this package in order to add [Sentry support](https://github.com/getsentry/sentry-dotnet).

Our current hook on ASP.NET Core is over `IWebHostBuilder` with `UseSentry`.
For what I could see so far, the `Startup` we can plug in only exposes `ConfigureServices` and `Configure`. Is there a way to hook into `IWebHostBuilder` or is it planned to be added? Thanks.

**Comment by jskeet** [comment]
Will look into this on Monday.

**Comment by bruno-garcia** [comment]
Thanks @jskeet.

Also, please note it's likely I can hook as a Startup class instead which will be nicer anyway for the client. I'll update this issue with the progress

**Comment by bruno-garcia** [comment]
I believe the best way to integrate, if I understand correctly, is for us to ship: `Sentry.Google.Cloud.Functions` with our own class extending `FunctionsStartup`. This way the users can simply add: `[assembly: FunctionsStartup(typeof(SentryCloudStartup))]` or similar.

It'll be possible to hook through `ConfigureLogging` and `ConfigureServices` alone, although `IWebHostBuilder` would be more convenient.

While attempting that I hit #145.

**Comment by jskeet** [comment]
I've just answered on #145, but you're absolutely right that creating a `FunctionsStartup` would be the best approach - that will allow users to integrate with Sentry just by adding a package reference and an assembly attribute.

The tricky part about providing access to `IWebHostBuilder` is controlling timing - some use cases would want to do something very early, other use cases would want to do it late.

An alternative for more complete control is to create the builder yourself, ignoring the EntryPoint code entirely (which also requires the same MSBuild property specified in the other issue). The Functions integration code is designed to be reasonably easily incorporated into custom configurations - see [the EntryPoint code](https://github.com/GoogleCloudPlatform/functions-framework-dotnet/blob/master/src/Google.Cloud.Functions.Hosting/EntryPoint.cs#L62) for what we do. (Although I've noticed there's currently some poor indentation near the end, which I'll fix next week.) The downside of this manual integration is that if we ever need to add more steps, they wouldn't be included automatically.

The *hope* was that the `FunctionsStartup` class would provide all the flexibility required, but if you could suggest any extra features for how you'd *like* to be able to get at the `IWebHostBuilder` (in a way that doesn't make too many timing assumptions) I'm definitely open to making changes.

**Comment by bruno-garcia** [comment]
That makes sense, thanks for the detailed explanation!

Lukily I didn't have to go the route of the `EntryPoint`.

I just gave it [a try with the `FunctionsStartup`](https://github.com/getsentry/sentry-dotnet/blob/feat/gcp-cloud-functions/src/Sentry.Google.Cloud.Functions/Startup.cs) and it plugged in really well on top of the existent ASP.NET Core integration. It's a draft but it can show what this could look like.

[Here's what the consumer would look like](https://github.com/getsentry/sentry-dotnet/blob/feat/gcp-cloud-functions/samples/Sentry.Samples.Google.Cloud.Functions/Function.cs).

And finally [what we can capture from that crash.](https://github.com/getsentry/sentry-dotnet/tree/feat/gcp-cloud-functions/samples/Sentry.Samples.Google.Cloud.Functions).

I'm closing this issue since from my perspective the current hook is great!

**Comment by jskeet** [comment]
I'm so pleased it works - looks great from a consumer perspective, too. It's so nice to see an *actual* integration in the way I'd envisaged. Thanks so much for your work on this.
