### ISSUE TITLE
Can't compile library with dependency to G.C.F.Hosting v 1.0.0-alpha12

### ISSUE THREAD

**Issue by bruno-garcia** [GoogleCloudPlatform/functions-framework-dotnet#145]
I'm having problems compiling a library once I add the dependency:

`<PackageReference Include="Google.Cloud.Functions.Hosting" Version="1.0.0-alpha12" />`

The repro is here: https://github.com/bruno-garcia/repro-google-cloud-functions

I tried to find any indication that `Google.Cloud.Functions.Hosting` compiles as an application instead of a library but I couldn't. Not sure what's wrong.

**Comment by jskeet** [comment]
Aha - I believe I know what's going on here. Basically this is the "magic" that is normally useful for automatically launching the function working against you. You need to disable that in your project.

In your `PropertyGroup` element, add:

```xml
<AutoGenerateEntryPoint>false</AutoGenerateEntryPoint>
```

I definitely need to document this, so I'll leave the issue open for that even if it works for you (it allows me to build your repro locally). Please confirm that this is the case though... and if you have any suggestions for *where* within the documentation this would be best, that would be really useful too.

**Comment by bruno-garcia** [comment]
Good catch, that indeed fixed the problem.

Perhaps a section on the docs for "Extending this library" or something? Since this is likely only going to affect projects that don't build an executable.

Or maybe there's a way around it with MSBuild by checking if `OutputType == Exe` to conditionally add `AutoGenerateEntryPoint`?

**Comment by jskeet** [comment]
Will start off by adding documentation. I suspect that checking with MSBuild properties *may* have sharp corners - it's certainly an area I don't have much experience in. It does sound promising though. Thanks for confirming that this sorts it out!

**Comment by jskeet** [comment]
It looks like checking OutputType at the point of *using* AutoGenerateEntryPoint is fine - I believe that using it to only *set* AutoGenerateEntryPoint would be more fiddly due to timing. I've got a PR out now to address this.

**Comment by jskeet** [comment]
The check for OutputType went out in 1.0.0-alpha13 - you should be able to target that without the MSBuild property. Please let me know if there are still any problems. (There may be corner cases I haven't thought about.)

**Comment by bruno-garcia** [comment]
Thanks for the update @jskeet !
