### ISSUE TITLE
Deployed functions contain .net core SDK and function source code

### ISSUE THREAD

**Issue by alteredego** [GoogleCloudPlatform/functions-framework-dotnet#167]
This is not a problem with this repo / code library, but when deploying a c# function, the resulting function container appears to contain the function source code and .net core SDK rather than it being an optimised runtime container?

I've posted this to the Cloud Functions Beta Testers group but not had a response, and I'm not sure where else to raise this as an issue.

**Comment by jskeet** [comment]
Sorry that you haven't had a response in the tester group, but I did see it - I've passed it on to the product manager who will be talking to the buildpack/runtime team involved. I'll close this issue now as any changes won't happen here.

**Comment by alteredego** [comment]
Superstar, many thanks.
