### ISSUE TITLE
Could you provide an example of CloudEventDataConverterAttribute

### ISSUE THREAD

**Issue by jchannon** [GoogleCloudPlatform/functions-framework-dotnet#180]
I have the below simple event function:

```fsharp
open Google.Cloud.Functions.Framework
open Google.Events
open Google.Events.Protobuf.Cloud.PubSub.V1
open System.Threading.Tasks

type Function() =
    interface ICloudEventFunction<PubsubMessage> with
        
        member this.HandleAsync(cloudEvent, data, cancellationToken) =

            printfn "%s" data.TextData

            Task.CompletedTask
```

When deployed I get the error:

```
System.InvalidOperationException: Unable to create data converter for target type Google.Events.Protobuf.Cloud.PubSub.V1.PubsubMessage
 ---> System.ArgumentException: Type Google.Events.Protobuf.Cloud.PubSub.V1.PubsubMessage does not have CloudEventDataConverterAttribute applied to it.
   at Google.Events.CloudEventConverters.CreateDataConverter[T]()
   --- End of inner exception stack trace ---
   at Google.Events.CloudEventConverters.CreateDataConverter[T]()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Google.Events.CloudEventConverters.GetDataConverter[T]()
   at Google.Events.CloudEventConverters.ConvertCloudEventData[T](CloudEvent cloudEvent)
   at Google.Cloud.Functions.Framework.CloudEventAdapter`1.HandleAsync(HttpContext context)
   at Google.Cloud.Functions.Hosting.HostingInternals.Execute(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

The README says the type in the `ICloudEventFunction` should have the `CloudEventDataConverterAttribute` applied to it but I would have thought GCP types would already have this?

Could you give an example of how to apply `CloudEventDataConverterAttribute` to types?

**Comment by jskeet** [comment]
Yes, you shouldn't need to do anything yourself. The trick here is that `PubsubMessage` isn't the right type here - you want `MessagePublishedData`, which has the attribute as shown here:

https://github.com/googleapis/google-cloudevents-dotnet/blob/master/src/Google.Events.Protobuf/Cloud/PubSub/V1/MessagePublishedData.g.cs

That then *contains* a `PubsubMessage`.

See https://cloud.google.com/functions/docs/calling/pubsub#functions_calling_pubsub-csharp for a sample function.

**Comment by jchannon** [comment]
Thanks!

**Comment by vestigialdev** [comment]
The "PubSub trigger" template for .NET generated by the web frontend has this problem

**Comment by jskeet** [comment]
@vestigialdev: I don't know what you mean by "this problem", or indeed what you mean by "the web frontend". Could you file a new issue with more details?

**Comment by jskeet** [comment]
@vestigialdev: Ah, hang on - do you mean the template in https://console.cloud.google.com/functions/add uses `PubsubMessage` rather than `MessagePublishedData`? Will check and fix if that's the case.

**Comment by vestigialdev** [comment]
Sorry for being unclear- I do mean that the template generated by the Cloud Console (rather than using powershell locally to run dotnet new gcf-event) seems to output a bad Function.cs that doesn't compile/deploy

**Comment by jskeet** [comment]
@vestigialdev: Yup - sorry for taking too long to work out that's what you meant. (First coffee of the day hadn't fully kicked in.)

It turns out there were issues with some other snippets too. I'm fixing those up, and also trying to work out why this wasn't caught in automated testing. Thanks for spotting it and drawing my attention to it.
