### ISSUE TITLE
TestServer process hanging around after test

### ISSUE THREAD

**Issue by jchannon** [GoogleCloudPlatform/functions-framework-dotnet#182]
In Rider after I run a test that inherits from `FunctionTestBase` I get the below warning from Rider after a while.  I have usually seen this when `TestServer` or the `HttpClient` from calling `TestServer.CreateClient` is not disposed but after a brief look into` FunctionTestBase` and `FunctionTestServer` the `Dispose` methods look ok and clients are marked inside a using clause so I'm unsure what causes this warning. 

Perhaps my gut feeling is wrong and something else is keeping the process alive. 

I'm on MacOS Big Sur.

![Screenshot 2021-01-08 at 11 30 46](https://user-images.githubusercontent.com/105126/104010863-1d6bf480-51a5-11eb-812d-98d5f047d8b6.png)

**Comment by jskeet** [comment]
Is whatever is running your test disposing of it? That happens automatically in xUnit, but I suspect it may not happen in some other test frameworks. If you could provide a complete example so that I can try to reproduce the issue, that would help. (Although I haven't used Rider and I don't have a Mac, so I'll need to see if I can reproduce it on Windows in VS...)

**Comment by jchannon** [comment]
I've just done a simple example to replicate it in F#

```fsharp
type FunctionTests() =
    inherit FunctionTestBase<Function>()

    [<Fact>]
    let functionTest () = Assert.Equal(1, 1)
```

**Comment by jskeet** [comment]
So I assume that `Fact` attribute is the xUnit one? (The test framework in use is definitely an important part here.)

**Comment by jchannon** [comment]
Yup xUnit

**Comment by jskeet** [comment]
Okay, I'll try to reproduce it when I have a chance - but that may well be next week.

**Comment by jchannon** [comment]
no rush, thanks

**Comment by jchannon** [comment]
no rush, thanks

**Comment by jskeet** [comment]
Reproduced in Rider using only the tests within the examples solution - in particular `SimpleHttpFunctionTest_WithFunctionTestBase`. Now looking into why that causes a problem.

**Comment by jskeet** [comment]
Progress of a kind: I can reproduce it without the Functions Framework being involved at all:

```csharp
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.Hosting;
using Xunit;

namespace SimpleTestProject
{
    public class UnitTest1
    {
        [Fact]
        public async Task CreateServerAndDispose()
        {
            var host = Host.CreateDefaultBuilder()
                .ConfigureWebHostDefaults(builder => builder.UseTestServer()
                    .Configure(app => app.Run(HandleRequest)))
                .Build();
            host.Start();
            using var testServer = host.GetTestServer();
            var client = testServer.CreateClient();
            var response = await client.GetAsync("/uri");
            response.EnsureSuccessStatusCode();
            var responseText = await response.Content.ReadAsStringAsync();
            Assert.Equal("Response from HandleRequest", responseText);
        }

        private static async Task HandleRequest(HttpContext context)
        {
            await context.Response.WriteAsync("Response from HandleRequest");
        }
    }
}
```

That's using Microsoft.AspNetCore.TestHost version 3.1.3... I'm going to see whether using a more recent version helps.

**Comment by jchannon** [comment]
Try putting this:

`using var client = testServer.CreateClient();`

**Comment by jskeet** [comment]
That doesn't help, but disposing of the *host* does. Which is a bit odd, given that `TestServer.Dispose` is (I believe) meant to dispose the underlying host. (It still fails with 3.1.10, btw.)

Ah - looking at https://github.com/dotnet/aspnetcore/blob/master/src/Hosting/TestHost/src/TestServer.cs, `Dispose` only does the right thing if the "right" `TestServer` constructor is called. Which is a bit grim and brittle really.

Fixing this will require a little fiddling with `FunctionTestServerBuilder` - but that should be doable. I *think* I can do it without any public API changes, too...

**Comment by jskeet** [comment]
This is now fixed in the main branch, but we're not planning on doing a release imminently, so you won't see it fixed just yet.

**Comment by jchannon** [comment]
np thanks

**Comment by jchannon** [comment]
Any ETA on a release or a chance to use a CI package?

**Comment by jskeet** [comment]
We don't have a CI NuGet source, I'm afraid. We have a few event conversion changes coming up which would be nice to include in a new build - I'll *try* to get to those (and then a release) next week, but I'm not promising...

**Comment by jchannon** [comment]
Thanks
