### ISSUE TITLE
Deploy binaries

### ISSUE THREAD

**Issue by AshleyMedway** [GoogleCloudPlatform/functions-framework-dotnet#185]
Maybe a stupid question but does the deployment have to use uncompiled code?

I am just thinking of fitting this into our current CI/CD process where we build in Azure DevOps and transform/deploy packages using Octopus.

Of course I can have Azure DevOps zip the code as the "build" and have Octopus run "gcloud functions deploy" if that is the requirement. Just wanted to make sure I am not missing something.

Thanks,
Ashley

**Comment by jskeet** [comment]
Good question. I don't *think* there's a way of doing that within "gcloud functions deploy" at the moment, but I'll check.

One alternative would be to deploy to Cloud Run, of course - the Functions Framework doesn't rely on anything from GCF specifically.

**Comment by AshleyMedway** [comment]
Might not be an option for me, looking for a pubsub trigger. I suppose I could always go the old subscribe to http workaround.

![image](https://user-images.githubusercontent.com/1255596/104584353-6109a700-565a-11eb-99fc-5365a780d8d8.png)

I'm europe-west2 unfortunately

**Comment by jskeet** [comment]
Hmm... I hope in the longer term that limitation will be resolved separately.

In the meantime, as another workaround you could *try* creating a csproj file that basically copies the output from your previous build as if it's the result of *this* build. Definitely clunky, but worth a try.

I'll raise this with the product team though.

**Comment by jskeet** [comment]
I've looked into this a bit more and talked with the product team. It's a supported scenario in Java, so there's nothing "philosophical" preventing it. Basically we'd need the dotnet3 buildpack to recognize that what has been uploaded is an already-published application.

I've filed a [Buildpack issue](https://github.com/GoogleCloudPlatform/buildpacks/issues/113) for this; I'll close this issue now as I wouldn't expect any change in *this* repository (beyond potentially a documentation note) - please subscribe to the Buildpack issue for updates.
