### ISSUE TITLE
Deployment message doesn't take into account build time

### ISSUE THREAD

**Issue by AshleyMedway** [GoogleCloudPlatform/functions-framework-dotnet#188]
I know this is hardly big picture stuff but when running `gcloud functions deploy` you get the following message:

```
Deploying function (may take a while - up to 2 minutes)...
```

With a large build it can take significantly longer than two minutes. It would be nice if there where two types of message, something like:

```
Compiling function (may take a while)...
Deploying function (may take a while - up to 2 minutes)...
```

Just thought I'd mention because in my case it takes over 5 minutes which might cause some confusion.

Thanks,
Ashley

**Comment by jskeet** [comment]
Thanks - I'll pass that on as a feature request. I'm not sure how feasibly it will be to separate out the stages in terms of feedback, but I can at least ask.

**Comment by jskeet** [comment]
I've filed an internal issue; I'll close this now as there's nothing we can do to influence it within *this* repo.
