### ISSUE TITLE
JsonConsoleLogger and SimpleConsoleLogger do not support BeginScope

### ISSUE THREAD

**Issue by SHackauf** [GoogleCloudPlatform/functions-framework-dotnet#193]
I wrote the following code and was expecting, that the logger will write the scope keys (in my example key, JobId and fileName inside the logging. When I checked the logging on the UI the keys are not written. 

``` csharp
using (this._logger.BeginScope(new Dictionary<string, object> { ["key"] = "1234567890123", ["jobId"] = 54 }))
{
    this._logger.LogTrace("Test Log - Scope Map - Trace");
    this._logger.LogDebug("Test Log - Scope Map - Debug");
    this._logger.LogInformation("Test Log - Scope Map - Information");
    this._logger.LogWarning("Test Log - Scope Map - Warning");
    this._logger.LogError("Test Log - Scope Map - Error");
    this._logger.LogError(new Exception("My Error Exception"), "Test Log - Scope Map - Error with Exception");
    this._logger.LogCritical("Test Log - Scope Map - Critical");
    this._logger.LogCritical(new Exception("My Critical Exception"), "Test Log - Scope Map - Critical with Exception");

    using (this._logger.BeginScope(new Dictionary<string, object> { ["fileName"] = "Test.txt" }))
    {
        this._logger.LogTrace("Test Log - Scope File - Trace");
        this._logger.LogDebug("Test Log - Scope File - Debug");
        this._logger.LogInformation("Test Log - Scope File - Information");
        this._logger.LogWarning("Test Log - Scope File - Warning");
        this._logger.LogError("Test Log - Scope File - Error");
        this._logger.LogError(new Exception("My Error Exception"), "Test Log - Scope File - Error with Exception");
        this._logger.LogCritical("Test Log - Scope File - Critical");
        this._logger.LogCritical(new Exception("My Critical Exception"), "Test Log - Scope File - Critical with Exception");
    }
}
```

Maybe it could be an option to include a third logger in the framework, where an output format string can be set via dependency injection. Inside this format string, the scope properties could be used when they are set. 

Example: "{scope:jobId} {scope:key} {message}"

Alternatively the logger could write the scope to the JsonPayload.

**Comment by jskeet** [comment]
> Maybe it could be an option to include a third logger in the framework, where an output format string can be set via dependency injection.

Well, you can replace the logger entirely yourself via a startup class if you really want to. I'd rather not have additional configuration within the framework itself - at least not at the moment.

But including scopes in the *default* logger makes sense, and I'll look at that when I get a chance.

**Comment by SHackauf** [comment]
Thanks for the fast response. 

I know of the change the logger inside the StartUp. I used at the moment the workaround to use the **NLog.Extension.Logging** together with **Google.Cloud.Logging.NLog**. That works. Unfortunately, I do not see the written logs on the Cloud function dialog on the UI. I only can search for them in the general logging dialog. But that is for the workaround ok.

**Comment by jskeet** [comment]
> Unfortunately, I do not see the written logs on the Cloud function dialog on the UI. I only can search for them in the general logging dialog.

It should be feasible to fix that by configuring the resource name appropriately. But I wouldn't suggest spending too long on that - I do hope to get this fixed next week, and I'll look at our NLog integration as a first pass for how to do it in the JSON logger.

**Comment by jskeet** [comment]
Okay, I've started working on this, and it mostly seems fairly simple. There are a couple of interesting options though:

- Is it actually useful to show scopes in the simple console log? (Current code includes them.)
- When there aren't any scopes, should we emit an empty array, or just nothing? (Current code emits an empty array in JSON, but not in the simple console log.)

While I would normally expect scopes to be useful in the simple console log, they do clutter up the "request starting" part quite a lot. Here's what I see with my current code:

```text
2021-01-26T08:52:40.515Z [Microsoft.AspNetCore.Hosting.Diagnostics] [info] [{ RequestId: 0HM61QUUEUGDB:00000001, RequestPath: /, SpanId: |f66aaaf6-403decf5795771a4., TraceId: f66aaaf6-403decf5795771a4, ParentId:  }] Request starting HTTP/1.1 GET http://localhost:8080/
```

That's not a problem - and could well be useful information - with the JSON formatter, of course.

The "do we emit an empty array for scopes in the JSON formatter" question is at least partly for convenience. It's not easy (at least using the external scope provider approach I'm using at the moment) to detect whether or not there *are* any scopes. So we'd need to write to a different JSON writer, then see if it's empty... which is a bit ugly. Emitting an empty array also provides more consistency - although only for log entries written by the Functions Framework itself (rather than the surrounding infrastructure).

This is what the JSON looks like for the nested example in the first comment:

![Scopes](https://user-images.githubusercontent.com/17011/105829644-8d0f1b80-5fbc-11eb-85c2-4216261c6c5e.png)

@SHackauf: Feedback welcome on all of this

@amanda-tarafa: Any thoughts?

**Comment by amanda-tarafa** [comment]
> * Is it actually useful to show scopes in the simple console log? (Current code includes them.)

Yes, I think it is, else someone using scopes needs to configure something other than console logging to see them. For development specially, that could be a hazzle. And they will show only for users that are adding them, so it shouldn't be unexpected clutter.

> * When there aren't any scopes, should we emit an empty array, or just nothing? (Current code emits an empty array in JSON, but not in the simple console log.)

Ideally I would prefer just nothing for JSON as well. Mostly to be consistent with the rest of entries that don't have any scopes. But this is really a NIT, and I'm fine with the empty array given that it makes implementation cleaner.

**Comment by jskeet** [comment]
> And they will show only for users that are adding them, so it shouldn't be unexpected clutter.

That's true for manual log entries - but not for the "Request starting" and "Request ending" ones (see above). We *could* detect those and special-case them, but that would be pretty ugly.

**Comment by amanda-tarafa** [comment]
> > And they will show only for users that are adding them, so it shouldn't be unexpected clutter.
> 
> That's true for manual log entries - but not for the "Request starting" and "Request ending" ones (see above). We _could_ detect those and special-case them, but that would be pretty ugly.

True, these entries are added by ASP.NET Core. Is there a simple way to configure the automatic scopes for those entries that we could expose? Beyond the clutter, it has happened before that users confuse the ASP.NET Core Span and Trace ID with the Google Cloud ones and try to find Google Cloud entries by those. But that can be easily explained away so I don't think it's a big deal.

**Comment by jskeet** [comment]
Related: https://github.com/dotnet/extensions/issues/1883

(In fact, writing the scopes to a separate line in the output, in the same way that we do for exceptions, might make it sufficiently non-chatty... same amount of information, but clearer. Will give that a go.)

**Comment by jskeet** [comment]
Here's a sample with the simple console log for a single request. There are three manually-written log entries

- One with no scopes
- One with a single scope
- One with two scopes

(The information in the scopes is as per the top comment)

```text
2021-01-26T11:50:03.742Z [Microsoft.AspNetCore.Hosting.Diagnostics] [info] Request starting HTTP/1.1 GET http://localhost:8080/
Scopes: [{ RequestId: 0HM61U22CLC7G:00000001, RequestPath: /, SpanId: |d1a139c9-4820bdf0ee64dbe7., TraceId: d1a139c9-4820bdf0ee64dbe7, ParentId:  }]
2021-01-26T11:50:03.746Z [Google.Cloud.Functions.Examples.SimpleHttpFunction.Function] [info] No scopes
2021-01-26T11:50:03.746Z [Google.Cloud.Functions.Examples.SimpleHttpFunction.Function] [info] Test Log - Scope Map - Information
Scopes: [{ key: 1234567890123, jobId: 54 }]
2021-01-26T11:50:03.746Z [Google.Cloud.Functions.Examples.SimpleHttpFunction.Function] [info] Test Log - Scope File - Information
Scopes: [{ key: 1234567890123, jobId: 54 }, { fileName: Test.txt }]
2021-01-26T11:50:03.751Z [Microsoft.AspNetCore.Hosting.Diagnostics] [info] Request finished in 10.8843ms 200
Scopes: [{ RequestId: 0HM61U22CLC7G:00000001, RequestPath: /, SpanId: |d1a139c9-4820bdf0ee64dbe7., TraceId: d1a139c9-4820bdf0ee64dbe7, ParentId:  }]
```

We're already breaking the "one entry per line" for exceptions, so this is just a similar approach. (And the fact that it's not used when deployed to GCF, instead getting the JSON log, means I'm not *too* worried.)

**Comment by SHackauf** [comment]
> Is it actually useful to show scopes in the simple console log? (Current code includes them.)

- In my opinion, it would make sense to write the scopes on the console log too. That is the easiest way to use the logger. Sure we could add a configuration, but that makes it in my opinion too complicated and the need I do not see. 
- The scopes from ASP.NET Core I would print out. Otherwise, it will be a surprise for developers who want to see them. Let me say it in other words: If the ASP.NET Core team thinks that are useful scopes I would use them also.
- The writing of the scopes in the console log in two rows I like a lot. When you have only one row and you use a lot of scopes you do not see the important output of your message. With the second line, it is much easier to read. 
- Do you have a screenshot how the two-row writing looks like on the Google Log Ui?

**One question about the two-row writing**
What happens if I have a lot of traffic on my Cloud Functions and there are running a lot of parallel instances of my function? Are the "normal" log row and the "Scope" row every time under each other or can it happen that the log output from another instance would come between?

> When there aren't any scopes, should we emit an empty array, or just nothing? (Current code emits an empty array in JSON, but not in the simple console log.)

If it is not as difficult I would not write an empty array. From my feeling, I would say most developers do not use scopes and maybe they are surprised if they see an empty array inside the JSON log. On the other hand, maybe they see it and think ... yes ... scopes I did not think about .. why not use them

**Comment by jskeet** [comment]
@SHackauf: Writing in two rows only happens when using the "simple" logger, which is basically when you're running locally.

If you're running in GCF (or in Cloud Run) the framework will use JSON automatically, and write it all in a single line. I think that addresses quite a few of your questions :)

I'll see if I can work out a way of handling the array bit simply and reasonably efficiently... I agree that it would be cleaner without them.

**Comment by jskeet** [comment]
Okay, I've worked out a way to handle omitting scopes in the JSON logger. I think I now have everything I need to take this to a PR - I just need to write a bunch of tests. With other work I've got on, that *may* end up going into next week I'm afraid, but at least I've got everything I need to proceed.

**Comment by jskeet** [comment]
Right, this will be in the next release - I'm going to see which other issues I can pick off before we do a release though.
