### ISSUE TITLE
Set tmp directory in configuration

### ISSUE THREAD

**Issue by SHackauf** [GoogleCloudPlatform/functions-framework-dotnet#194]
All directories of the cloud function are writing protected. When a temp directory is needed you need to use **\tmp**. 

Maybe it would be nice if the base functions of the DOTNET framework would add the temp folder inside the IConfigurationBuilder. 

```
builder.AddInMemoryCollection(
                new Dictionary<string, string>
                {
                    { "CLOUDTEMP", "/tmp" }
                }
            );
```

**Sure my example does not work like that**, because when you run the function inside Visual Studio or on a Windows system the directory does not exist. 

Maybe a director check could help for that. I could imagine something like the following:
```
private static string GetTempDirectory(FunctionsStartup startup)
{
    var gcfTempDirectory = "/tmp";
    var tempPath = Directory.Exists(gcfTempDirectory) ? gcfTempDirectory : string.Empty;

    if (string.IsNullOrEmpty(tempPath))
    {
        try
        {
            var binDirectory = Path.GetDirectoryName(startup.GetType().GetTypeInfo().Assembly.Location) ?? string.Empty;
            var binTempDirectory = Path.Combine(binDirectory, "tmp");

            if (!Directory.Exists(binTempDirectory))
            {
                Directory.CreateDirectory(binTempDirectory);
            }

            tempPath = binTempDirectory;
        }
        catch (Exception)
        {
            // do nothing
        }
    }
    
    return tempPath;
}
```

**Comment by jskeet** [comment]
Hmmm... maybe. I'm not entirely sure about this right now, but I'll think about it.

Is there any benefit to this over [Path.GetTempPath](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=net-5.0)? I'd have to check what that does on Linux, but I'd really expect it to return "/tmp".

**Comment by jskeet** [comment]
Okay, I've just tried this on my Windows box, and then deploying to GCF, to see the result of `Path.GetTempPath()`:

- Windows: `C:\Users\[my-user-name]\AppData\Local\Temp\`
- GCF: `/tmp/`

That feels like that should be sufficient - do you agree? If so, we can close this feature request. If not, please give more information.

**Comment by SHackauf** [comment]
Yes, that is completely enough. During all my test of the implementation, I oversaw the Path.GetTempPath() option. Issue is closed now.
