### ISSUE TITLE
LogLevel.Debug set with logger.LogDebug("foo") fails to appear in logs

### ISSUE THREAD

**Issue by jchannon** [GoogleCloudPlatform/functions-framework-dotnet#200]
I have LogLevel.Debug set in appsettings.json but when I use `ILogger.LogDebug("foo")` these fail to appear in the logs in Log Explorer within GCP. Seems the minimum it works on is LogInformation

**Comment by jskeet** [comment]
Will try to look at that on Monday.

Note that you should be able to test this easily locally without deploying to GCP - just use `dotnet run` and you should see the logs on the console. That should make it much easier to diagnose.

If you could provide a minimal example (including appsettings.json) that would be appreciated, but otherwise I suspect I can reproduce it fairly easily...

**Comment by jskeet** [comment]
Just as a thought - are you sure you're *showing* debug log entries in the log explorer? (It's not clear to me whether you mean the log explorer within the Functions console, or the general GCP log viewer, but both of them have filter levels and I *suspect* they'll filter out debug logs by default.) Check the filter.

**Comment by jchannon** [comment]
Hmm that wouldn't surprise me however I can't see any filters applied

![Screenshot 2021-03-05 at 18 18 05](https://user-images.githubusercontent.com/105126/110156857-62945780-7ddf-11eb-9bda-7d312d1207b8.png)

**Comment by jskeet** [comment]
Thanks for the screenshot - that helps a lot.

Trying to reproduce now (as a meeting finished early).

**Comment by jchannon** [comment]
![Screenshot 2021-03-05 at 18 33 17](https://user-images.githubusercontent.com/105126/110158441-4d202d00-7de1-11eb-860a-b4a2fc5236b8.png)

**Comment by jchannon** [comment]
![Screenshot 2021-03-05 at 18 35 20](https://user-images.githubusercontent.com/105126/110158670-92445f00-7de1-11eb-88a3-353db51771f6.png)

Example here!

**Comment by jskeet** [comment]
For the future, examples are rather easier to reproduce with text than with pictures, but I've managed to reproduce the issue (with a C# example, which is a more convenient environment for me to experiment in, too).

My current *guess* is that appsettings.json isn't being detected/used properly, but I'll need to check that out on Monday.

**Comment by jskeet** [comment]
Right - I'm now reasonably confident that it is indeed around the internal configuration and appsettings.json. If I add a startup class which overrides `ConfigureLogging` with `logging.SetMinimumLevel(LogLevel.Debug)` (and remove appsettings.json entirely) then it works fine.

So either the appsettings.json file isn't being copied correctly, or it's not being picked up at all... we have an example which uses appsettings.json, so I'm sure I've had it working before. Will look in more detail on Monday. But until then, if you want a workaround you can use the startup class...

**Comment by jchannon** [comment]
Thanks

I did set the equivalent environment variable but that didn’t get picked up
either

**Comment by jskeet** [comment]
Not sure which environment variable you meant, by the way. We can look at that separately.

But I do now understand why it's not working with appsettings.json: that isn't being published by default.

I'll create a more general issue for that, but in the meantime, you can work around it by adding this into your project file, in the `ItemGroup` element:

```xml
<None Update="appsettings*.json" CopyToOutputDirectory="PreserveNewest" />
```

I'm going to see whether I can make that the default behavior for apps depending on Google.Cloud.Functions.Hosting, but it needs to be done with a certain amount of care.

**Comment by jchannon** [comment]
I was referring to LOGGING__LOGLEVEL__DEFAULT env var

**Comment by jskeet** [comment]
Ah, I see... using the automatic "infer config from environment variables" in ASP.NET Core. Will have to see if I can work out what that wasn't working.

**Comment by jskeet** [comment]
I've just successfully seen debug log entries using that environment variable.

I deployed it with this command line:

```sh
 gcloud functions deploy issue-200 --runtime=dotnet3 --entry-point=Issue200.Function --trigger-http --set-env-vars=LOGGING__LOGLEVEL__DEFAULT=Debug
```

Could you let me know how you tried to set the environment variable, when it wasn't working for you?

**Comment by jchannon** [comment]
It was probably set in my terraform file

**Comment by jskeet** [comment]
Okay... not having any experience of Terraform, I can't really comment on that - but it sounds like it's probably Terraform-specific, given that it works both locally and when deploying with `gcloud functions deploy` - I suspect it's a more general issue of "setting environment variables for use in a Function" than a .NET specific aspect.

I'll close this issue now as I don't think there's anything logging-specific left; issue #201 covers the more general problem of appsettings.json not being copied when the app is published.
