### ISSUE TITLE
appsettings.json not deployed as it's not published

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/functions-framework-dotnet#201]
In our configuration example, we use appsettings.json... but this isn't actually deployed by default. For now, we can fix the example by adding an entry to the project file of:

```xml
<None Update="appsettings*.json" CopyToOutputDirectory="PreserveNewest" />
```

... but it would be nice for this not to be required. It's not clear what *other* files should be copied in the same way. We should probably look at what (and how) ASP.NET Core does this normally.

**Comment by jchannon** [comment]
I've just double checked this and my project had

`<Content Include="appsettings.json" />` and I still had debug log levels not appearing
 
I changed it to your suggestion and still didn't have the output

**Comment by jchannon** [comment]
Here's a repro https://github.com/jchannon/functionsfwkbug

**Comment by jskeet** [comment]
Okay, I'll try the repro, thanks. (I'm *hoping* this isn't an F# vs C# difference...)

**Comment by jskeet** [comment]
Aha... for F# it needs to be `Include` rather than `Update`... but this works with the repro:

```xml
    <ItemGroup>
        <Compile Include="Function.fs" />
        <None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
```

**Comment by jskeet** [comment]
I've just looked at this for Azure Functions, and the Azure Functions default project templates seem to come with entries by default:

```xml
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
```

So maybe rather than try to be clever, we should just update our templates to include `AppSettings*.json` with CopyToOutputDirectory=PreserveNewest.
