### ISSUE TITLE
Is it possible to create HTTPS Callable Function?

### ISSUE THREAD

**Issue by dex3r** [GoogleCloudPlatform/functions-framework-dotnet#204]
Can I somehow use functions-framework-dotnet to create HTTPS Callable Function from "Cloud Functions for Firebase"?
I am not talking about creating functions from code (like in JS), I just want to manually create a function, that I can call from Firebase SDK in my client?

https://firebase.google.com/docs/functions/callable

I've created a simple function, it's called on the backend side just fine, however in my client it throw an Internal API Error.

I realize it's not possible natively, but is it even possible for me to write support for this myself? If so, can you please nudge me in the right direction? :)

**Comment by jskeet** [comment]
Hmm... I don't know - I'll have to ask folks internally on Monday. Will get back to you when I have more information.

**Comment by mbleigh** [comment]
Callable functions are HTTP functions that obey a wire protocol [documented here](https://firebase.google.com/docs/functions/callable-reference). If you write a function without using the `firebase-functions` SDK that follows all of the protocol, it should be compatible with the client-side callable functions SDKs.

**Comment by jskeet** [comment]
@dex3r: Does that answer your question? My guess is that your response isn't a JSON object containing error/data. I'm happy to help with the .NET function side of things, but I don't know anything about the Firebase side beyond the documentation that @mbleigh linked to.

**Comment by jskeet** [comment]
While I don't know very much about the Firebase Admin SDK, I don't know if any reason why you shouldn't use the [Google.Cloud.Firestore](http://googleapis.dev/dotnet/Google.Cloud.Firestore/latest) package (you'll want to use that rather than Google.Cloud.Firestore.V1 directly) and the FirebaseAdmin package together. It's *definitely* okay to use the Google.Cloud.Firestore package from Google Cloud Functions.

**Comment by dex3r** [comment]
It seems that simple response JSON formatting did the trick. 

I'll attach my "response object" code for reference. Note: this is by no means a complete implementation, it does however work with basic response and error handling by Firebse Client SDK.

```
using Newtonsoft.Json;

[JsonObject]
public class CallableResponse
{
	// ReSharper disable InconsistentNaming
	[JsonObject]
	private class Error
	{
		[JsonProperty(NullValueHandling = NullValueHandling.Include)]
		public string message;
		
		[JsonProperty(NullValueHandling = NullValueHandling.Include)]
		public string status;
	}
	
	[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
	private object data;
	
	[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
	private Error error;

	private CallableResponse(object _data, Error _error)
	{
		data = _data;
		error = _error;
	}
	// ReSharper restore InconsistentNaming
	
	public static CallableResponse Success(object dataObject) => new CallableResponse(dataObject, null);

	public static CallableResponse Failed(string message) => new CallableResponse(null, new Error {message = message, status = "INTERNAL"});

	public override string ToString() => JsonConvert.SerializeObject(this);

	public static implicit operator string(CallableResponse value) => value.ToString();
}
```

Example usage snippet inside `HandleAsync`:
```
		string responseJsonString = CallableResponse.Success(response);
		await context.Response.WriteAsync(responseJsonString);
	}
	catch (Exception e)
	{
		_logger.LogError($"Exception: {e}");
		
		string responseErrorString = CallableResponse.Failed(e.Message);

		context.Response.StatusCode = 500;
		await context.Response.WriteAsync(responseErrorString);
	}
```

**Comment by jskeet** [comment]
Thanks - glad it worked :)

As a suggestion, to avoid the inconsistent naming warnings, I'd suggest:

- Using properties instead of fields
- Using normal C# naming (so `Data`, `Error`, `Message`, `Status`)
- Using `[JsonProperty("data")]` etc to specify the names used within the JSON

I'll close this issue now as it sounds like it's all sorted. Hooray!

**Comment by dex3r** [comment]
@jskeet yeah I was split between those two naming options and went the way above ;). You are right, yours is probably better. Thanks.
