### ISSUE TITLE
How to capture the function context route name?

### ISSUE THREAD

**Issue by lucas-zimerman** [GoogleCloudPlatform/functions-framework-dotnet#224]
I'm asking this because neither
```csharp
context.GetEndpoint()?.Metadata.GetMetadata<EndpointNameMetadata>()?.EndpointName
```
and
```csharp
var endpoint = context.Features.Get<IEndpointFeature?>()?.Endpoint as RouteEndpoint;
var routePattern = endpoint?.RoutePattern.RawText;
```
seems to be giving me any value. Is there another approach for retrieving the route name using GCP?

**Comment by jskeet** [comment]
There's no such concept as a route within the Functions Framework. (There's no routing because *all* requests go to the same function.) It's not entirely clear to me what you're looking for.

**Comment by lucas-zimerman** [comment]
I see, thanks for the clarification jskeet.
