### ISSUE TITLE
How to retrieve some data from the Function?

### ISSUE THREAD

**Issue by lucas-zimerman** [GoogleCloudPlatform/functions-framework-dotnet#227]
I'd like to get the data from the function inside of the C# code, the data are the following:
* Function region
* Function Name
* GCP Project

I'm aware that it's possible to retrieve such values with the Python integration by doing
```python
environ.get("FUNCTION_NAME")
environ.get("GCP_PROJECT")
environ.get("FUNCTION_REGION")
```

**Comment by jskeet** [comment]
I don't believe any of those are available at the moment in the .NET Functions Framework. If they were present, I'd expect them to be in environment variables - there's `FUNCTION_TARGET` but none of the others.

I can look into how the Python runtime determines these - they may well be available somewhere in the file system, for example.

**Comment by josephlewis42** [comment]
You should be able to make a `GET` request to `http://metadata.google.internal/computeMetadata/v1/?recursive=true` with the header `Metadata-Flavor: Google` to retrieve this information from the attached metadata server. You can see a list of [specific paths if you only want a few values](https://cloud.google.com/compute/docs/metadata/default-metadata-values) and don't want to parse the JSON response.

Those environment variables in Python are only available in [older versions](https://cloud.google.com/functions/docs/configuring/env-var#python_37_and_go_111).
