### ISSUE TITLE
.NET Core 6 Support

### ISSUE THREAD

**Issue by AshleyMedway** [GoogleCloudPlatform/functions-framework-dotnet#229]
Now that .net 6 is officially released is there a timeline for support to come to functions?

**Comment by cwillison94** [comment]
Is there any update on this?

With .NET Core 3.1 end of life less than a year away (December 3, 2022), I was hoping for an official .NET 6 support date.

**Comment by jskeet** [comment]
No dates to give at the moment, I'm afraid. The GCF team is aware that there's demand, but I'll pass on your sense of urgency (and particularly its relation to the .NET Core 3.1 support timeline).

**Comment by alteredego** [comment]
Sorry to pester.  Can someone provide an update/timeline for when this might be available/supported?  I can see this really reducing/simplifying function code, as well as having performance improvements.  I noticed AWS Lambda recently added .NET 6 support.  Thanks in advance!

**Comment by jskeet** [comment]
No more updates to provide, I'm afraid.

**Comment by ffecteau30** [comment]
@grant @jskeet Any update on this? Would be nice to have a date for .net 6 support

**Comment by grant** [comment]
> @grant @jskeet @matthewrobertson Any update on this? Would be nice to have a date for .net 6 support.

One of the first tasks to enable .NET Core 6 support (or any language support) on GCF would be to properly test the Functions Framework with that version of the runtime. After, adding [buildpack](https://github.com/googleCloudPlatform/buildpacks) support for dotnet6.

These parts are open sourced and would allow for `gcloud run deploy --source .` experience. These parts would be required for support with Functions. I haven't explored the effort it would take for these projects.

**Comment by AshleyMedway** [comment]
For anyone waiting for this it might be better/easier to move to Cloud Run.

In Cloud Run you create your own docker image so have complete control over the .NET version and with the eventarc api you can configure the same triggers. This way you’ll also be able to move to .NET 7 which functions will not support as Google have said they will only support the LTS versions. 

If anyone wants a guide on converting a function to Cloud Run let me know as we’ve done this for some of our production functions and plan to do the rest by the end of the month.

**Comment by AlbertoMonteiro** [comment]
@AshleyMedway for those using PubSub with push subscription, can pubsub trigger the CloudRun in some private way?

**Comment by AshleyMedway** [comment]
@AlbertoMonteiro we use the eventarc triggers to trigger CloudRun from PubSub. You can't remove the web endpoint but you can set it to internal only.

![image](https://user-images.githubusercontent.com/1255596/164092072-6d823b8f-1927-40d1-a196-c28da817ede5.png)

**Comment by AlbertoMonteiro** [comment]
Nice @AshleyMedway in that way how does dead letter and retry work?

**Comment by AshleyMedway** [comment]
@AlbertoMonteiro essentially it just creates a subscription so you can fully configure it

![image](https://user-images.githubusercontent.com/1255596/164110935-e914a261-5eb0-4fff-a265-044a19f83853.png)

**Comment by AlbertoMonteiro** [comment]
Perfect, thank you very much

**Comment by jskeet** [comment]
Just as a heads-up, I don't have dates to promise or anything like that right now, but there *is* work on this taking place.

**Comment by Zylanx** [comment]
Perfect to hear. This is exactly the issue I am having right now and back porting to a .net runtime now 2 versions out is a bit of a pain.
Thanks for the heads up!
