### ISSUE TITLE
Support for health probes in CloudEvent functions

### ISSUE THREAD

**Issue by lance** [GoogleCloudPlatform/functions-framework-dotnet#231]
When specifying a Container object in Kubernetes, it is possible to specify both a `readinessProbe` and a `livenessProbe` which inform the system that the application is healthy. In Knative, these endpoints may also be specified in the Container section of a Service. However, one thing that Knative does differently is that if not specified, Knative considers "container startup and listening on the declared HTTP socket" sufficient. [[reference](https://github.com/knative/specs/blob/main/specs/serving/runtime-contract.md#meta-requests)].

The implication of this is that, for readiness probes, Knative is performing a `GET /` request on container startup if these health endpoints are not specified when the Service is deployed. Unfortunately, it seems that this is unsupported with this framework. When I create a CloudEvent project and run it locally, I get this error in the logs when sending a `GET /`.

```
2021-11-30T18:37:56.229Z [Microsoft.AspNetCore.Hosting.Diagnostics] [info] Request starting HTTP/1.1 HEAD http://localhost:8080/
Scopes: [{ RequestId: 0HMDK611GE70C:00000001, RequestPath: /, SpanId: |9977183-4d03947d96083f6c., TraceId: 9977183-4d03947d96083f6c, ParentId:  }]
2021-11-30T18:37:56.231Z [Google.Cloud.Functions.Framework.CloudEventAdapter] [fail] Unable to convert request to CloudEvent.
2021-11-30T18:37:56.231Z [Microsoft.AspNetCore.Hosting.Diagnostics] [info] Request finished in 2.2379ms 400
Scopes: [{ RequestId: 0HMDK611GE70C:00000001, RequestPath: /, SpanId: |9977183-4d03947d96083f6c., TraceId: 9977183-4d03947d96083f6c, ParentId:  }]
```

And the caller gets a 400 level error.

The end result is that I cannot deploy a CloudEvents function to Knative because the Service never enters the ready state. It would be nice if this framework allowed me to do any one of the following.

- Use it in Knative for CloudEvents with predetermined health endpoints
- Use it in Knative for CloudEvents with health endpoints that I can configure
- Use it in Knative for CloudEvents with support for `GET /`

If it is already possible somehow to do any of the above, can you please provide a doc reference - and my apologies for the oversight.

Note: I have opened similar issues in the Node.js and Ruby frameworks. I suspect other such as Python behave similarly, but have not tested these.

**Comment by jskeet** [comment]
Thanks, I'll talk to the team internally about this.

**Comment by jskeet** [comment]
Hi Lance,

Sorry for the very long wait before getting a response on this. We discussed it on Friday. Thanks for the clear description of the problem, and I definitely understand it.

There are multiple ways we *could* solve this problem - we'd like to wait until we hear more requirements from other customers who are in a "similar but potentially slightly different" situation so that we can try to build something that works for everyone. (Other features we're considering *might* allow an easy workaround for this, too.)

Can I assume that there's no way of persuading Knative to post a precanned CloudEvent with a special ID so that you could just return immediately? That would be a pretty horrible hack, but if it's feasible it might at least unblock you.

**Comment by lance** [comment]
> Can I assume that there's no way of persuading Knative to post a precanned CloudEvent with a special ID so that you could just return immediately? That would be a pretty horrible hack, but if it's feasible it might at least unblock you.

It's OK! I opened the issue as an information point, not because I was blocked. I had been doing some experiments with the Node.js functions framework and noticed this problem, so I thought I would look at others to see if it was common across languages. Thanks for getting back to me. I am glad you all have a path forward with this, but be aware that there is no rush from my perspective.

**Comment by jskeet** [comment]
Aha - that's good to hear. I'll leave this open, at least for now, so we don't forget about it. (If we implement it, I expect we'll do it uniformly across all Functions Frameworks as best we can.)
