### ISSUE TITLE
Inconsistent result from localhost runtime and deployed runtime

### ISSUE THREAD

**Issue by AllThingsBeingEqual** [GoogleCloudPlatform/functions-framework-dotnet#233]
I am getting an error in a function that works when running on the local `host.`

`    public class CallerFunction : IHttpFunction  {
        
        public async Task HandleAsync(HttpContext context) {
            HttpRequest request = context.Request;
            HttpResponse response = context.Response;
            using TextReader reader = new StreamReader(request.Body);
            string text = await reader.ReadLineAsync();
            if (text == null) {
                string someString = "No Text Provided";
                await response.WriteAsync(someString);
            } else
            {
                string someString = text;
                await response.WriteAsync(someString);
            }
        }
    }
`

I am using Postman for all of these HTTPS calls.

curl --location --request GET 'localhost:8080' \
--header 'Content-Type: text/plain' \
--data-raw 'My name is Fred'

returns "My name is Fred"

curl --location --request GET 'localhost:8080'

returns "No Text Provided"

curl --location --request GET 'https://us-central1-myGCProject.cloudfunctions.net/myProjectName/'

returns "No Text Provided"

curl --location --request GET 'https://us-central1-organism-3301.cloudfunctions.net/organism/' \
--header 'Content-Type: text/plain' \
--data-raw 'my name is fred'

returns Error 400 (Bad Request)

I would be very happy to hear that there is something I am doing wrong.  I was not able to find any examples on how to include content in the HTTP.

**Comment by jskeet** [comment]
I'll have a look on Monday, but isn't it quite odd to send data with a GET request? Have you tried doing the same thing with post?

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET:

> Sending body/payload in a GET request may cause some existing implementations to reject the request — while not prohibited by the specification, the semantics are undefined. It is better to just avoid sending payloads in GET requests.

**Comment by AllThingsBeingEqual** [comment]
Many thanks for the quick response.  You are correct - POST - solved the problem.  

CONCLUSION:  Do not use GET.  That is easy to remember and satisifes my project requirements (my recommend to other users make a note of this as well).

************************************************************************************************
Background that may make clear why I don't think I will be the only person likely to take this path.

I had used GET because the 'GET' seems to me to be more inline with a function. 

  _Use GET requests to retrieve resource representation/information only – and not modify it in any way. As GET requests do not change the resource’s state, these are said to be safe methods.
  
  Additionally, GET APIs should be idempotent. Making multiple identical requests must produce the same result every time until another API (POST or PUT) has changed the state of the resource on the server.__

I am calling a cloud fuction with arguments (sent as text). The function it is idempotent (without any  POST or PUT  call support).  Think of reciving a string and returning the same string in all caps.  Intuitively it would seem that this would be a GET with someString sent in the body and a return value.  

We are migrating a C# function from Azure Functions to GC Functions (reason is that this endpoint will serve a the endpoint for a Google Apps Script URL Fetch Service).  I am not sufficiently expert to say which is more correct but Azure appears to also be agnostic on GET or POST for function requests.  

What you have provided in the dotnet framework is great in the simplicity to implement (seen in the example code) pretty much takes care of passing strings in request and response.   

Again thanks for the quick response and appolgies for the lengthy response.


P.S.
I will commit to providing an example, showing what I am doing once I have a better idea what I am doing.
