### ISSUE TITLE
Provide CancellationToken Support in Cloud HTTP Functions

### ISSUE THREAD

**Issue by bt-Knodel** [GoogleCloudPlatform/functions-framework-dotnet#255]
HttpContext has a "request aborted", but in our testing it does not appear that HTTP Functions actually cause this cancellation token to trigger if the client disconnections.

Could support for this be added?  We have some cloud functions that are relatively heavy and if cancelled, it could help reduce impact if Cancellation Tokens were properly supported in HTTP functions

**Comment by jskeet** [comment]
I would expect Kestrel to handle this for us - that's what's doing all the HTTP. I'll investigate.

**Comment by jskeet** [comment]
Okay, I *think* this is a matter of the GCF runtime itself not detecting that the request has been aborted. Here's a sample function:

```csharp
using Google.Cloud.Functions.Framework;
using Microsoft.AspNetCore.Http;
using System;
using System.Threading.Tasks;

namespace RequestCancellation
{
    public class Function : IHttpFunction
    {
        public async Task HandleAsync(HttpContext context)
        {
            try
            {
                for (int i = 0; i < 10; i++)
                {
                    Console.WriteLine($"Waiting - iteration {i}");
                    await Task.Delay(1000, context.RequestAborted);
                }
            }
            catch (TaskCanceledException e)
            {
                Console.WriteLine($"Task canceled: {e}");
            }
        }
    }
}
```

When I run that locally, open a browser to execute the function, then close the tab/window after a few seconds, I see log entries showing that the cancellation token has been aborted. So the .NET Functions Framework is definitely able to detect that.

However, running the same function in GCF, I see logs for iterations 0-9, and the cancellation token is never cancelled.

Assigning to Annie for any further steps.

**Comment by josephlewis42** [comment]
This is a known issue with Cloud Functions, but there's currently no ETA on when it'll be resolved. I'm going to close this issue for the dotnet framework since it seems like once Cloud Functions resolves this this framework won't need to be updated.
