### ISSUE TITLE
Create Visual Studio templates?

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/functions-framework-dotnet#28]
It's nice having "dotnet new" templates, but it would be even nicer to be able to use them in VS itself. It feels like that should be feasible without duplication - need to investigate.

**Comment by jskeet** [comment]
Blog post: https://www.jimbobbennett.io/creating-visual-studio-project-and-solution-templates-part-2-vs-for-windows-extension-2/

**Comment by jskeet** [comment]
Hmm. Sidewaffle looks like it _may_ be dead. See https://github.com/ligershark/sidewafflev2/issues/48

**Comment by jskeet** [comment]
This issue is worth following, for VS support of "dotnet new" templates: https://github.com/dotnet/templating/issues/481

**Comment by jskeet** [comment]
Sidewaffle download: https://github.com/ligershark/SideWaffleWebsite/blob/master/SideWaffleWebsite/feed/web/SideWaffle.Creator.v1.1.vsix

**Comment by Tetsuoryuu** [comment]
This is definitely something that would streamline the developer experience and would reduce the chances of creating a wrong template for your project via CLI.

**Comment by jskeet** [comment]
Looks like there's progress on this: https://github.com/dotnet/templating/issues/481

**Comment by jskeet** [comment]
It's now available in VS 2019 Preview version 16.8.0-preview-2.1.

Will leave this issue open for the sake of tweaking the wording.

**Comment by jskeet** [comment]
More guidance: https://github.com/sayedihashimi/template-sample
