### ISSUE TITLE
Document deployment in .NET 8

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/functions-framework-dotnet#444]
There's a `dotnet8` runtime, currently in beta. I've tested that it works with a very simple function:

- Use the normal template (gcf-http)
- Edit the project file to change `net6.0` to `net8.0` (for `TargetFramework`)
- Use functionality only available in .NET 8 (some JSON options in this particular case)
- Deploy with the command below

```sh
$ gcloud beta functions deploy test-dotnet-8 --runtime=dotnet8 --entry-point=TestDotnet8.Function \
    --trigger-http --allow-unauthenticated --gen2
```

It worked first time...

Note that it's gen2 only.

It's possible (likely?) that this is still using the .NET 6 version of ASP.NET Core, as that's what the Functions Framework targets - but adding an explicit dependency *might* address that; more work to be done there.

At some point we should document all of this, and maybe eventually change the templates.

**Comment by giammin** [comment]
Is it possible to deploy a function published as Native AOT?

**Comment by jskeet** [comment]
@giammin: Not at the moment as far as I'm aware. Unfortunately I don't have time to spend on researching current options and future possibilities at the moment. (I really would like to...)

**Comment by arnigunnar** [comment]
@jskeet, is it possible to use the `dotnet7` runtime? And have all projects target `net7.0`?

**Comment by jskeet** [comment]
@arnigunnar: I don't know for sure, but I wouldn't expect that to be supported. It makes more sense for us only to support LTS releases.

**Comment by AlbertoMonteiro** [comment]
> [@giammin](https://github.com/giammin): Not at the moment as far as I'm aware. Unfortunately I don't have time to spend on researching current options and future possibilities at the moment. (I really would like to...)

Hey @jskeet is there any AoT plans or not?

**Comment by jskeet** [comment]
@AlbertoMonteiro: Not imminently, I'm afraid. I really don't have any time to spend on the Functions Framework at the moment. We hope to get a release out targeting .NET 8 (I know, I know - lots of internal stuff I can't get into) but I'm not expecting to have time to do anything else on it unless serious bugs come up, to be honest.

**Comment by AlbertoMonteiro** [comment]
Thanks for the follow-up @jskeet !!!
