### ISSUE TITLE
Alarming log entries about heartbeats

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/functions-framework-dotnet#48]
As a function starts, it logs something like this:

> Heartbeat took longer than "00:00:01" at "04/23/2020 15:11:27 +00:00". This could be caused by thread pool starvation.

(The category is "Microsoft.AspNetCore.Server.Kestrel".)

That's a bit alarming - but probably not an actual problem. Perhaps we should silently swallow those log entries?

**Comment by jskeet** [comment]
Interestingly, I don't see this on all functions - I do for all my "google.com" functions, but not my personal account ones. Weird.

**Comment by amanda-tarafa** [comment]
Have you check the default log level for the deployments, if such thing exists. Might be related to internal policy?

**Comment by jskeet** [comment]
I don't *think* that's it... but I'll see what I can find out. I might disable the JSON logging so it's all just regular console logging, and see if that makes a difference. (I want to make that configurable anyway...)
