### ISSUE TITLE
Deploy to Cloud Functions in GCP

### ISSUE THREAD

**Issue by hlaueriksson** [GoogleCloudPlatform/functions-framework-dotnet#6]
How do I deploy my function to Cloud Functions in Google Cloud Platform?
When I create a new function I can only see Go, Node.js and Python runtimes.

**Comment by jskeet** [comment]
We're not quite ready for that yet - there are a few bits missing before you'll be able to use this in GCF, but we're working on it.
I'll ping this bug when we've got something ready for (very early) testing.

**Comment by jskeet** [comment]
I've now [documented](https://github.com/GoogleCloudPlatform/functions-framework-dotnet/blob/master/docs/deployment.md) how to deploy to GCF if you're on an allow-list. We don't yet have a public sign-up for that, but it'll come soon and I'll update the docs appropriately at that point.
