### ISSUE TITLE
Support for Legacy Cloud Storage and Pubsub triggers?

### ISSUE THREAD

**Issue by hdp617** [GoogleCloudPlatform/functions-framework-dotnet#70]
GCF functions can be triggered by legacy object change notifications [0]. These events have type `providers/cloud.storage/eventTypes/object.change` that is currently not supported in the Functions Framework for .NET [1].

I assume it can be done by mapping from `providers/cloud.storage/eventTypes/object.change` to something like `com.google.cloud.storage.object.change.v0`.

- Do we want to support this?

Happy to send a PR.

[0] https://cloud.google.com/functions/docs/calling/storage#legacy_cloud_storage_triggers
[1] https://github.com/GoogleCloudPlatform/functions-framework-dotnet/blob/e0a05d96c68ef1dcd557c1d03c7b1426c7dcce90/src/Google.Cloud.Functions.Framework/GcfEvents/GcfConverters.cs#L36-L44

**Comment by jskeet** [comment]
Does this look anything like the other events, i.e. will the conversion from legacy event to Cloud Event work as-is? If so, it absolutely makes sense to support it.
If not, we might want to wait until there are other bits of code performing the conversion to Cloud Events.

I'll give it a try on Monday and see how it goes, and log my results here.

**Comment by hdp617** [comment]
> Does this look anything like the other events, i.e. will the conversion from legacy event to Cloud Event work as-is?

Yes, I think the only difference is the event name. In the other frameworks, there's no special logic for such events.

Also, I've discovered there's also a legacy event type for PubSub [0]. These legacy event types look a lot like the Firestore ones.

> I'll give it a try on Monday and see how it goes, and log my results here.

Thanks Jon!

[0] https://cloud.google.com/functions/docs/calling/pubsub#legacy_cloud_pubsub_triggers
