### ISSUE TITLE
Support Signature Type: CloudEvent

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-dotnet#77]
## Support signature type `cloudevent`

This signature type should support HTTP requests with CloudEvent objects delivered via either structured and binary CloudEvent objects. Usually a CloudEvents SDK can handle transforming the HTTP request to a language-native CloudEvent object.

New change in **Functions Framework contract**: 
https://github.com/GoogleCloudPlatform/functions-framework#cloudevents-functions-signature-type-cloudevent

The end-user should see the parameter `cloudevent`, which is a native CloudEvent object using the CloudEvent SDK if possible. For example, in Node, the CloudEvent handler would look like this:

### Example handler in Node

```js
function handler(cloudevent) {
  console.log(cloudevent.id);
  console.log(cloudevent.data);
}
```

### Example payload

```json
{
    "specversion" : "1.0",
    "type" : "com.github.pull.create",
    "source" : "https://github.com/cloudevents/spec/pull",
    "subject" : "123",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : { "custom": "foo", "number": 123 }
}
```

**Comment by jskeet** [comment]
It's not clear what this requires that isn't already covered.

We have the [non-generic `ICloudEventFunction` interface](https://github.com/GoogleCloudPlatform/functions-framework-dotnet/blob/60bc846fee8be35893997151dde841f7eb1438db/src/Google.Cloud.Functions.Framework/ICloudEventFunction.cs#L24) that doesn't perform any kind of deserialization, and the [generic `ICloudEventFunction<TData>`](https://github.com/GoogleCloudPlatform/functions-framework-dotnet/blob/60bc846fee8be35893997151dde841f7eb1438db/src/Google.Cloud.Functions.Framework/ICloudEventFunction.cs#L41) that deserializes the data from the cloud event automatically.

**Comment by grant** [comment]
Note I created this issue for all 7 frameworks. I think .NET is probably the most up-to-date with respect to this.
If there is support for CloudEvents, structured and binary formats, then we can close this issue.

**Comment by jskeet** [comment]
Yup, sounds like we're fine. Closing.
