### ISSUE TITLE
Problem adding a Connected WCF / SOAP service 

### ISSUE THREAD

**Issue by Tetsuoryuu** [GoogleCloudPlatform/functions-framework-dotnet#99]
I wanted to import a WCF service to my IHttpFunction but I keep getting these errors: 

![image](https://user-images.githubusercontent.com/2069783/87203662-041fe380-c2fb-11ea-8d29-71aa4c5db477.png)
![image](https://user-images.githubusercontent.com/2069783/87204310-65948200-c2fc-11ea-942c-a92946ca37e2.png)

I have tried adding different endpoints HTTP and HTTPS, generating synchronous or asynchronous operations, but nothing seems work.

Is this currently possible?

**Comment by jskeet** [comment]
Thanks for raising this - I'll look into it on Monday.

**Comment by jskeet** [comment]
Apologies for not looking at this before.

It looks like the WCF importer tooling is *running* the project... I'm not sure why it would do that, or what it expects to happen.

As a workaround, are you able to import the service into a regular ASP.NET Core project, then copy the code (and any project settings) into your function project?

I'll try reproducing this myself later today, following https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x as a guide. It may be that we can't make it work seamlessly, but that we can document a workaround.

**Comment by Tetsuoryuu** [comment]
Yes I tried that and it works.

Besides copying the generated class I had to add 4 required Packages through Nuget / Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Functions.Invoker" Version="1.0.0-alpha07" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.7.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.7.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.7.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Connected Services\" />
  </ItemGroup>
</Project>
```

**Comment by jskeet** [comment]
I'm making progress with this - I *think* we'll be able to make it work by adding a Condition to the dependency in the project file, so that when svcutil runs it effectively ignores that dependency. I've got to work out exactly how to phrase the condition though...
